/* 
 * ChronoSheets API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CsApiUpdateOrganisationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CsApiUpdateOrganisationResponseTests
    {
        // TODO uncomment below to declare an instance variable for CsApiUpdateOrganisationResponse
        //private CsApiUpdateOrganisationResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CsApiUpdateOrganisationResponse
            //instance = new CsApiUpdateOrganisationResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CsApiUpdateOrganisationResponse
        /// </summary>
        [Test]
        public void CsApiUpdateOrganisationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CsApiUpdateOrganisationResponse
            //Assert.IsInstanceOfType<CsApiUpdateOrganisationResponse> (instance, "variable 'instance' is a CsApiUpdateOrganisationResponse");
        }


        /// <summary>
        /// Test the property 'ValidationErrors'
        /// </summary>
        [Test]
        public void ValidationErrorsTest()
        {
            // TODO unit test for the property 'ValidationErrors'
        }

    }

}
