/* 
 * ChronoSheets API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CsApiProjectCostingReportItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CsApiProjectCostingReportItemTests
    {
        // TODO uncomment below to declare an instance variable for CsApiProjectCostingReportItem
        //private CsApiProjectCostingReportItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CsApiProjectCostingReportItem
            //instance = new CsApiProjectCostingReportItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CsApiProjectCostingReportItem
        /// </summary>
        [Test]
        public void CsApiProjectCostingReportItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CsApiProjectCostingReportItem
            //Assert.IsInstanceOfType<CsApiProjectCostingReportItem> (instance, "variable 'instance' is a CsApiProjectCostingReportItem");
        }


        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'ProjectName'
        /// </summary>
        [Test]
        public void ProjectNameTest()
        {
            // TODO unit test for the property 'ProjectName'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Test]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }
        /// <summary>
        /// Test the property 'ClientName'
        /// </summary>
        [Test]
        public void ClientNameTest()
        {
            // TODO unit test for the property 'ClientName'
        }
        /// <summary>
        /// Test the property 'EstimatedCost'
        /// </summary>
        [Test]
        public void EstimatedCostTest()
        {
            // TODO unit test for the property 'EstimatedCost'
        }
        /// <summary>
        /// Test the property 'ActualCost'
        /// </summary>
        [Test]
        public void ActualCostTest()
        {
            // TODO unit test for the property 'ActualCost'
        }

    }

}
