/* 
 * ChronoSheets API
 *
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CsApiInsertJobCodeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CsApiInsertJobCodeRequestTests
    {
        // TODO uncomment below to declare an instance variable for CsApiInsertJobCodeRequest
        //private CsApiInsertJobCodeRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CsApiInsertJobCodeRequest
            //instance = new CsApiInsertJobCodeRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CsApiInsertJobCodeRequest
        /// </summary>
        [Test]
        public void CsApiInsertJobCodeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CsApiInsertJobCodeRequest
            //Assert.IsInstanceOfType<CsApiInsertJobCodeRequest> (instance, "variable 'instance' is a CsApiInsertJobCodeRequest");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Test]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'LinkedTaskIds'
        /// </summary>
        [Test]
        public void LinkedTaskIdsTest()
        {
            // TODO unit test for the property 'LinkedTaskIds'
        }
        /// <summary>
        /// Test the property 'LinkedOrgGroupIds'
        /// </summary>
        [Test]
        public void LinkedOrgGroupIdsTest()
        {
            // TODO unit test for the property 'LinkedOrgGroupIds'
        }

    }

}
