/* 
 * ChronoSheets API Documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachmentTests
    {
        // TODO uncomment below to declare an instance variable for CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment
        //private CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment
            //instance = new CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment
        /// </summary>
        [Test]
        public void CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment
            //Assert.IsInstanceOfType<CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment> (instance, "variable 'instance' is a CsApiApiResponseForPaginatedListOrgReportTimesheetFileAttachment");
        }


        /// <summary>
        /// Test the property 'TotalSetCount'
        /// </summary>
        [Test]
        public void TotalSetCountTest()
        {
            // TODO unit test for the property 'TotalSetCount'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
