/* 
 * The ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  </p>  <p>      First Steps:       <ol>          <li>Make sure you've <a href='/HomeV2/App/sign-up'>signed up to ChronoSheets</a> to get yourself a user account</li>          <li>Confirm your account by following the link sent to your email address.  This will activate your account</li>          <li>Use your username and password to obtain an Auth Token by using the DoLogin method inside the UserProfile section below.  Use the Auth Token as an argument to the other methods</li>          <li>Try different methods in the API Playground to learn about the API</li>          <li>If you're stuck, try the full getting started guide on the <a href='/Home/ApiDocs'>API Toolkit</a> page.</li>      </ol>  </p>  <p>      Further Steps:       <ul>          <li>Create a mobile app (iOS, Android or Windows) using one of the ChronoSheets Mobile SDKs</li>          <li>Create a custom integration with your app using one of the ChronoSheets API Client Libraries.</li>      </ul>      Read more about the API Toolkit on the <a href='/Home/ApiDocs'>API Toolkit</a> page.  </p></div>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CSCombinedReportsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CSCombinedReportsDataTests
    {
        // TODO uncomment below to declare an instance variable for CSCombinedReportsData
        //private CSCombinedReportsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CSCombinedReportsData
            //instance = new CSCombinedReportsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CSCombinedReportsData
        /// </summary>
        [Test]
        public void CSCombinedReportsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CSCombinedReportsData
            //Assert.IsInstanceOfType<CSCombinedReportsData> (instance, "variable 'instance' is a CSCombinedReportsData");
        }


        /// <summary>
        /// Test the property 'SeriesJobCodes'
        /// </summary>
        [Test]
        public void SeriesJobCodesTest()
        {
            // TODO unit test for the property 'SeriesJobCodes'
        }
        /// <summary>
        /// Test the property 'SeriesTasks'
        /// </summary>
        [Test]
        public void SeriesTasksTest()
        {
            // TODO unit test for the property 'SeriesTasks'
        }
        /// <summary>
        /// Test the property 'SeriesClients'
        /// </summary>
        [Test]
        public void SeriesClientsTest()
        {
            // TODO unit test for the property 'SeriesClients'
        }
        /// <summary>
        /// Test the property 'SeriesProjects'
        /// </summary>
        [Test]
        public void SeriesProjectsTest()
        {
            // TODO unit test for the property 'SeriesProjects'
        }
        /// <summary>
        /// Test the property 'TotalsJobCodes'
        /// </summary>
        [Test]
        public void TotalsJobCodesTest()
        {
            // TODO unit test for the property 'TotalsJobCodes'
        }
        /// <summary>
        /// Test the property 'TotalsTasks'
        /// </summary>
        [Test]
        public void TotalsTasksTest()
        {
            // TODO unit test for the property 'TotalsTasks'
        }
        /// <summary>
        /// Test the property 'TotalsClients'
        /// </summary>
        [Test]
        public void TotalsClientsTest()
        {
            // TODO unit test for the property 'TotalsClients'
        }
        /// <summary>
        /// Test the property 'TotalsProjects'
        /// </summary>
        [Test]
        public void TotalsProjectsTest()
        {
            // TODO unit test for the property 'TotalsProjects'
        }

    }

}
