/* 
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CSCreateAutomationStepRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CSCreateAutomationStepRequestTests
    {
        // TODO uncomment below to declare an instance variable for CSCreateAutomationStepRequest
        //private CSCreateAutomationStepRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CSCreateAutomationStepRequest
            //instance = new CSCreateAutomationStepRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CSCreateAutomationStepRequest
        /// </summary>
        [Test]
        public void CSCreateAutomationStepRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CSCreateAutomationStepRequest
            //Assert.IsInstanceOfType<CSCreateAutomationStepRequest> (instance, "variable 'instance' is a CSCreateAutomationStepRequest");
        }


        /// <summary>
        /// Test the property 'GeofencingId'
        /// </summary>
        [Test]
        public void GeofencingIdTest()
        {
            // TODO unit test for the property 'GeofencingId'
        }
        /// <summary>
        /// Test the property 'NfcId'
        /// </summary>
        [Test]
        public void NfcIdTest()
        {
            // TODO unit test for the property 'NfcId'
        }
        /// <summary>
        /// Test the property 'AutomationActionType'
        /// </summary>
        [Test]
        public void AutomationActionTypeTest()
        {
            // TODO unit test for the property 'AutomationActionType'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Test]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Test]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
