/* 
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CSOrganisation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CSOrganisationTests
    {
        // TODO uncomment below to declare an instance variable for CSOrganisation
        //private CSOrganisation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CSOrganisation
            //instance = new CSOrganisation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CSOrganisation
        /// </summary>
        [Test]
        public void CSOrganisationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CSOrganisation
            //Assert.IsInstanceOfType<CSOrganisation> (instance, "variable 'instance' is a CSOrganisation");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'AddressLine01'
        /// </summary>
        [Test]
        public void AddressLine01Test()
        {
            // TODO unit test for the property 'AddressLine01'
        }
        /// <summary>
        /// Test the property 'AddressLine02'
        /// </summary>
        [Test]
        public void AddressLine02Test()
        {
            // TODO unit test for the property 'AddressLine02'
        }
        /// <summary>
        /// Test the property 'Suburb'
        /// </summary>
        [Test]
        public void SuburbTest()
        {
            // TODO unit test for the property 'Suburb'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Test]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Test]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
        /// <summary>
        /// Test the property 'SubscriptionCustomerId'
        /// </summary>
        [Test]
        public void SubscriptionCustomerIdTest()
        {
            // TODO unit test for the property 'SubscriptionCustomerId'
        }
        /// <summary>
        /// Test the property 'SignupToken'
        /// </summary>
        [Test]
        public void SignupTokenTest()
        {
            // TODO unit test for the property 'SignupToken'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'SubscriptionCycleStart'
        /// </summary>
        [Test]
        public void SubscriptionCycleStartTest()
        {
            // TODO unit test for the property 'SubscriptionCycleStart'
        }
        /// <summary>
        /// Test the property 'SubscriptionCycleEnd'
        /// </summary>
        [Test]
        public void SubscriptionCycleEndTest()
        {
            // TODO unit test for the property 'SubscriptionCycleEnd'
        }
        /// <summary>
        /// Test the property 'PricingPlans'
        /// </summary>
        [Test]
        public void PricingPlansTest()
        {
            // TODO unit test for the property 'PricingPlans'
        }

    }

}
