/* 
 * ChronoSheets API
 *
 * ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing CSTimeSlot
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CSTimeSlotTests
    {
        // TODO uncomment below to declare an instance variable for CSTimeSlot
        //private CSTimeSlot instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CSTimeSlot
            //instance = new CSTimeSlot();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CSTimeSlot
        /// </summary>
        [Test]
        public void CSTimeSlotInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CSTimeSlot
            //Assert.IsInstanceOfType<CSTimeSlot> (instance, "variable 'instance' is a CSTimeSlot");
        }


        /// <summary>
        /// Test the property 'DayType'
        /// </summary>
        [Test]
        public void DayTypeTest()
        {
            // TODO unit test for the property 'DayType'
        }
        /// <summary>
        /// Test the property 'UsualHourId'
        /// </summary>
        [Test]
        public void UsualHourIdTest()
        {
            // TODO unit test for the property 'UsualHourId'
        }
        /// <summary>
        /// Test the property 'StartHour'
        /// </summary>
        [Test]
        public void StartHourTest()
        {
            // TODO unit test for the property 'StartHour'
        }
        /// <summary>
        /// Test the property 'StartMinute'
        /// </summary>
        [Test]
        public void StartMinuteTest()
        {
            // TODO unit test for the property 'StartMinute'
        }
        /// <summary>
        /// Test the property 'EndHour'
        /// </summary>
        [Test]
        public void EndHourTest()
        {
            // TODO unit test for the property 'EndHour'
        }
        /// <summary>
        /// Test the property 'EndMinute'
        /// </summary>
        [Test]
        public void EndMinuteTest()
        {
            // TODO unit test for the property 'EndMinute'
        }
        /// <summary>
        /// Test the property 'IsValid'
        /// </summary>
        [Test]
        public void IsValidTest()
        {
            // TODO unit test for the property 'IsValid'
        }

    }

}
