/* 
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing UpdateOrganisationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateOrganisationRequestTests
    {
        // TODO uncomment below to declare an instance variable for UpdateOrganisationRequest
        //private UpdateOrganisationRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateOrganisationRequest
            //instance = new UpdateOrganisationRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateOrganisationRequest
        /// </summary>
        [Test]
        public void UpdateOrganisationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateOrganisationRequest
            //Assert.IsInstanceOf(typeof(UpdateOrganisationRequest), instance);
        }


        /// <summary>
        /// Test the property 'OrgansationId'
        /// </summary>
        [Test]
        public void OrgansationIdTest()
        {
            // TODO unit test for the property 'OrgansationId'
        }
        /// <summary>
        /// Test the property 'OrganisationName'
        /// </summary>
        [Test]
        public void OrganisationNameTest()
        {
            // TODO unit test for the property 'OrganisationName'
        }
        /// <summary>
        /// Test the property 'AddressLine01'
        /// </summary>
        [Test]
        public void AddressLine01Test()
        {
            // TODO unit test for the property 'AddressLine01'
        }
        /// <summary>
        /// Test the property 'AddressLine02'
        /// </summary>
        [Test]
        public void AddressLine02Test()
        {
            // TODO unit test for the property 'AddressLine02'
        }
        /// <summary>
        /// Test the property 'OrganisationSuburb'
        /// </summary>
        [Test]
        public void OrganisationSuburbTest()
        {
            // TODO unit test for the property 'OrganisationSuburb'
        }
        /// <summary>
        /// Test the property 'OrganisationState'
        /// </summary>
        [Test]
        public void OrganisationStateTest()
        {
            // TODO unit test for the property 'OrganisationState'
        }
        /// <summary>
        /// Test the property 'OrganisationPostcode'
        /// </summary>
        [Test]
        public void OrganisationPostcodeTest()
        {
            // TODO unit test for the property 'OrganisationPostcode'
        }
        /// <summary>
        /// Test the property 'OrganisationCountry'
        /// </summary>
        [Test]
        public void OrganisationCountryTest()
        {
            // TODO unit test for the property 'OrganisationCountry'
        }
        /// <summary>
        /// Test the property 'OrganisationPhone'
        /// </summary>
        [Test]
        public void OrganisationPhoneTest()
        {
            // TODO unit test for the property 'OrganisationPhone'
        }
        /// <summary>
        /// Test the property 'OrganisationEmailAddress'
        /// </summary>
        [Test]
        public void OrganisationEmailAddressTest()
        {
            // TODO unit test for the property 'OrganisationEmailAddress'
        }

    }

}
