/* 
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ChronoSheetsAPI.ChronoSheetsClientLibApi;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;
using ChronoSheetsAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ChronoSheetsAPI.Test
{
    /// <summary>
    ///  Class for testing UserHourlyRate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserHourlyRateTests
    {
        // TODO uncomment below to declare an instance variable for UserHourlyRate
        //private UserHourlyRate instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserHourlyRate
            //instance = new UserHourlyRate();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserHourlyRate
        /// </summary>
        [Test]
        public void UserHourlyRateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UserHourlyRate
            //Assert.IsInstanceOf(typeof(UserHourlyRate), instance);
        }


        /// <summary>
        /// Test the property 'RateId'
        /// </summary>
        [Test]
        public void RateIdTest()
        {
            // TODO unit test for the property 'RateId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'OrganisationId'
        /// </summary>
        [Test]
        public void OrganisationIdTest()
        {
            // TODO unit test for the property 'OrganisationId'
        }
        /// <summary>
        /// Test the property 'IsCurrent'
        /// </summary>
        [Test]
        public void IsCurrentTest()
        {
            // TODO unit test for the property 'IsCurrent'
        }
        /// <summary>
        /// Test the property 'HourlyRate'
        /// </summary>
        [Test]
        public void HourlyRateTest()
        {
            // TODO unit test for the property 'HourlyRate'
        }
        /// <summary>
        /// Test the property 'HourlyOvertimeRate'
        /// </summary>
        [Test]
        public void HourlyOvertimeRateTest()
        {
            // TODO unit test for the property 'HourlyOvertimeRate'
        }
        /// <summary>
        /// Test the property 'StartDateTime'
        /// </summary>
        [Test]
        public void StartDateTimeTest()
        {
            // TODO unit test for the property 'StartDateTime'
        }
        /// <summary>
        /// Test the property 'EndDateTime'
        /// </summary>
        [Test]
        public void EndDateTimeTest()
        {
            // TODO unit test for the property 'EndDateTime'
        }

    }

}
