/* 
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using ChronoSheetsAPI.Client;
using ChronoSheetsAPI.ChronoSheetsClientLibModel;

namespace ChronoSheetsAPI.ChronoSheetsClientLibApi
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserJobFavouritesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>ApiResponseInt32</returns>
        ApiResponseInt32 UserJobFavouritesCreateJobFavourite (string xChronosheetsAuth, InsertUserJobFavouriteRequest request);

        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>ApiResponse of ApiResponseInt32</returns>
        ApiResponse<ApiResponseInt32> UserJobFavouritesCreateJobFavouriteWithHttpInfo (string xChronosheetsAuth, InsertUserJobFavouriteRequest request);
        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponseBoolean</returns>
        ApiResponseBoolean UserJobFavouritesDeleteJobFavourite (int jobId, string xChronosheetsAuth);

        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponse of ApiResponseBoolean</returns>
        ApiResponse<ApiResponseBoolean> UserJobFavouritesDeleteJobFavouriteWithHttpInfo (int jobId, string xChronosheetsAuth);
        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponseListUserJobFavourite</returns>
        ApiResponseListUserJobFavourite UserJobFavouritesGetJobFavourites (string xChronosheetsAuth);

        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponse of ApiResponseListUserJobFavourite</returns>
        ApiResponse<ApiResponseListUserJobFavourite> UserJobFavouritesGetJobFavouritesWithHttpInfo (string xChronosheetsAuth);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>Task of ApiResponseInt32</returns>
        System.Threading.Tasks.Task<ApiResponseInt32> UserJobFavouritesCreateJobFavouriteAsync (string xChronosheetsAuth, InsertUserJobFavouriteRequest request);

        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>Task of ApiResponse (ApiResponseInt32)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponseInt32>> UserJobFavouritesCreateJobFavouriteAsyncWithHttpInfo (string xChronosheetsAuth, InsertUserJobFavouriteRequest request);
        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponseBoolean</returns>
        System.Threading.Tasks.Task<ApiResponseBoolean> UserJobFavouritesDeleteJobFavouriteAsync (int jobId, string xChronosheetsAuth);

        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponse (ApiResponseBoolean)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponseBoolean>> UserJobFavouritesDeleteJobFavouriteAsyncWithHttpInfo (int jobId, string xChronosheetsAuth);
        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponseListUserJobFavourite</returns>
        System.Threading.Tasks.Task<ApiResponseListUserJobFavourite> UserJobFavouritesGetJobFavouritesAsync (string xChronosheetsAuth);

        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponse (ApiResponseListUserJobFavourite)</returns>
        System.Threading.Tasks.Task<ApiResponse<ApiResponseListUserJobFavourite>> UserJobFavouritesGetJobFavouritesAsyncWithHttpInfo (string xChronosheetsAuth);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserJobFavouritesApi : IUserJobFavouritesApi
    {
        private ChronoSheetsAPI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserJobFavouritesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserJobFavouritesApi(String basePath)
        {
            this.Configuration = new ChronoSheetsAPI.Client.Configuration { BasePath = basePath };

            ExceptionFactory = ChronoSheetsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserJobFavouritesApi"/> class
        /// </summary>
        /// <returns></returns>
        public UserJobFavouritesApi()
        {
            this.Configuration = ChronoSheetsAPI.Client.Configuration.Default;

            ExceptionFactory = ChronoSheetsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserJobFavouritesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserJobFavouritesApi(ChronoSheetsAPI.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = ChronoSheetsAPI.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = ChronoSheetsAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public ChronoSheetsAPI.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ChronoSheetsAPI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>ApiResponseInt32</returns>
        public ApiResponseInt32 UserJobFavouritesCreateJobFavourite (string xChronosheetsAuth, InsertUserJobFavouriteRequest request)
        {
             ApiResponse<ApiResponseInt32> localVarResponse = UserJobFavouritesCreateJobFavouriteWithHttpInfo(xChronosheetsAuth, request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>ApiResponse of ApiResponseInt32</returns>
        public ApiResponse<ApiResponseInt32> UserJobFavouritesCreateJobFavouriteWithHttpInfo (string xChronosheetsAuth, InsertUserJobFavouriteRequest request)
        {
            // verify the required parameter 'xChronosheetsAuth' is set
            if (xChronosheetsAuth == null)
                throw new ApiException(400, "Missing required parameter 'xChronosheetsAuth' when calling UserJobFavouritesApi->UserJobFavouritesCreateJobFavourite");
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling UserJobFavouritesApi->UserJobFavouritesCreateJobFavourite");

            var localVarPath = "/UserJobFavourites/CreateJobFavourite";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded", 
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xChronosheetsAuth != null) localVarHeaderParams.Add("x-chronosheets-auth", this.Configuration.ApiClient.ParameterToString(xChronosheetsAuth)); // header parameter
            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserJobFavouritesCreateJobFavourite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponseInt32>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponseInt32) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponseInt32)));
        }

        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>Task of ApiResponseInt32</returns>
        public async System.Threading.Tasks.Task<ApiResponseInt32> UserJobFavouritesCreateJobFavouriteAsync (string xChronosheetsAuth, InsertUserJobFavouriteRequest request)
        {
             ApiResponse<ApiResponseInt32> localVarResponse = await UserJobFavouritesCreateJobFavouriteAsyncWithHttpInfo(xChronosheetsAuth, request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <param name="request">An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create</param>
        /// <returns>Task of ApiResponse (ApiResponseInt32)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponseInt32>> UserJobFavouritesCreateJobFavouriteAsyncWithHttpInfo (string xChronosheetsAuth, InsertUserJobFavouriteRequest request)
        {
            // verify the required parameter 'xChronosheetsAuth' is set
            if (xChronosheetsAuth == null)
                throw new ApiException(400, "Missing required parameter 'xChronosheetsAuth' when calling UserJobFavouritesApi->UserJobFavouritesCreateJobFavourite");
            // verify the required parameter 'request' is set
            if (request == null)
                throw new ApiException(400, "Missing required parameter 'request' when calling UserJobFavouritesApi->UserJobFavouritesCreateJobFavourite");

            var localVarPath = "/UserJobFavourites/CreateJobFavourite";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded", 
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xChronosheetsAuth != null) localVarHeaderParams.Add("x-chronosheets-auth", this.Configuration.ApiClient.ParameterToString(xChronosheetsAuth)); // header parameter
            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserJobFavouritesCreateJobFavourite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponseInt32>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponseInt32) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponseInt32)));
        }

        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponseBoolean</returns>
        public ApiResponseBoolean UserJobFavouritesDeleteJobFavourite (int jobId, string xChronosheetsAuth)
        {
             ApiResponse<ApiResponseBoolean> localVarResponse = UserJobFavouritesDeleteJobFavouriteWithHttpInfo(jobId, xChronosheetsAuth);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponse of ApiResponseBoolean</returns>
        public ApiResponse<ApiResponseBoolean> UserJobFavouritesDeleteJobFavouriteWithHttpInfo (int jobId, string xChronosheetsAuth)
        {
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new ApiException(400, "Missing required parameter 'jobId' when calling UserJobFavouritesApi->UserJobFavouritesDeleteJobFavourite");
            // verify the required parameter 'xChronosheetsAuth' is set
            if (xChronosheetsAuth == null)
                throw new ApiException(400, "Missing required parameter 'xChronosheetsAuth' when calling UserJobFavouritesApi->UserJobFavouritesDeleteJobFavourite");

            var localVarPath = "/UserJobFavourites/DeleteJobFavourite";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (jobId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "JobId", jobId)); // query parameter
            if (xChronosheetsAuth != null) localVarHeaderParams.Add("x-chronosheets-auth", this.Configuration.ApiClient.ParameterToString(xChronosheetsAuth)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserJobFavouritesDeleteJobFavourite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponseBoolean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponseBoolean) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponseBoolean)));
        }

        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponseBoolean</returns>
        public async System.Threading.Tasks.Task<ApiResponseBoolean> UserJobFavouritesDeleteJobFavouriteAsync (int jobId, string xChronosheetsAuth)
        {
             ApiResponse<ApiResponseBoolean> localVarResponse = await UserJobFavouritesDeleteJobFavouriteAsyncWithHttpInfo(jobId, xChronosheetsAuth);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Delete a job favourite.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="jobId">The ID of the Job for the Job Favourite you want to delete.</param>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponse (ApiResponseBoolean)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponseBoolean>> UserJobFavouritesDeleteJobFavouriteAsyncWithHttpInfo (int jobId, string xChronosheetsAuth)
        {
            // verify the required parameter 'jobId' is set
            if (jobId == null)
                throw new ApiException(400, "Missing required parameter 'jobId' when calling UserJobFavouritesApi->UserJobFavouritesDeleteJobFavourite");
            // verify the required parameter 'xChronosheetsAuth' is set
            if (xChronosheetsAuth == null)
                throw new ApiException(400, "Missing required parameter 'xChronosheetsAuth' when calling UserJobFavouritesApi->UserJobFavouritesDeleteJobFavourite");

            var localVarPath = "/UserJobFavourites/DeleteJobFavourite";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (jobId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "JobId", jobId)); // query parameter
            if (xChronosheetsAuth != null) localVarHeaderParams.Add("x-chronosheets-auth", this.Configuration.ApiClient.ParameterToString(xChronosheetsAuth)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserJobFavouritesDeleteJobFavourite", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponseBoolean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponseBoolean) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponseBoolean)));
        }

        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponseListUserJobFavourite</returns>
        public ApiResponseListUserJobFavourite UserJobFavouritesGetJobFavourites (string xChronosheetsAuth)
        {
             ApiResponse<ApiResponseListUserJobFavourite> localVarResponse = UserJobFavouritesGetJobFavouritesWithHttpInfo(xChronosheetsAuth);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>ApiResponse of ApiResponseListUserJobFavourite</returns>
        public ApiResponse<ApiResponseListUserJobFavourite> UserJobFavouritesGetJobFavouritesWithHttpInfo (string xChronosheetsAuth)
        {
            // verify the required parameter 'xChronosheetsAuth' is set
            if (xChronosheetsAuth == null)
                throw new ApiException(400, "Missing required parameter 'xChronosheetsAuth' when calling UserJobFavouritesApi->UserJobFavouritesGetJobFavourites");

            var localVarPath = "/UserJobFavourites/GetJobFavourites";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xChronosheetsAuth != null) localVarHeaderParams.Add("x-chronosheets-auth", this.Configuration.ApiClient.ParameterToString(xChronosheetsAuth)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserJobFavouritesGetJobFavourites", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponseListUserJobFavourite>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponseListUserJobFavourite) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponseListUserJobFavourite)));
        }

        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponseListUserJobFavourite</returns>
        public async System.Threading.Tasks.Task<ApiResponseListUserJobFavourite> UserJobFavouritesGetJobFavouritesAsync (string xChronosheetsAuth)
        {
             ApiResponse<ApiResponseListUserJobFavourite> localVarResponse = await UserJobFavouritesGetJobFavouritesAsyncWithHttpInfo(xChronosheetsAuth);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get your job favourites.    Requires the &#39;SubmitTimesheets&#39; permission. 
        /// </summary>
        /// <exception cref="ChronoSheetsAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xChronosheetsAuth">The ChronoSheets Auth Token</param>
        /// <returns>Task of ApiResponse (ApiResponseListUserJobFavourite)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ApiResponseListUserJobFavourite>> UserJobFavouritesGetJobFavouritesAsyncWithHttpInfo (string xChronosheetsAuth)
        {
            // verify the required parameter 'xChronosheetsAuth' is set
            if (xChronosheetsAuth == null)
                throw new ApiException(400, "Missing required parameter 'xChronosheetsAuth' when calling UserJobFavouritesApi->UserJobFavouritesGetJobFavourites");

            var localVarPath = "/UserJobFavourites/GetJobFavourites";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml",
                "multipart/form-data"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xChronosheetsAuth != null) localVarHeaderParams.Add("x-chronosheets-auth", this.Configuration.ApiClient.ParameterToString(xChronosheetsAuth)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UserJobFavouritesGetJobFavourites", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ApiResponseListUserJobFavourite>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (ApiResponseListUserJobFavourite) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ApiResponseListUserJobFavourite)));
        }

    }
}
