/* 
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ChronoSheetsAPI.Client.OpenAPIDateConverter;

namespace ChronoSheetsAPI.ChronoSheetsClientLibModel
{
    /// <summary>
    /// A basic geofence
    /// </summary>
    [DataContract]
    public partial class BasicGeofence :  IEquatable<BasicGeofence>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BasicGeofence" /> class.
        /// </summary>
        /// <param name="geoFencingId">The ID of the geofence.</param>
        /// <param name="name">The descriptive name of the geofence.</param>
        public BasicGeofence(int geoFencingId = default(int), string name = default(string))
        {
            this.GeoFencingId = geoFencingId;
            this.Name = name;
        }
        
        /// <summary>
        /// The ID of the geofence
        /// </summary>
        /// <value>The ID of the geofence</value>
        [DataMember(Name="GeoFencingId", EmitDefaultValue=false)]
        public int GeoFencingId { get; set; }

        /// <summary>
        /// The descriptive name of the geofence
        /// </summary>
        /// <value>The descriptive name of the geofence</value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BasicGeofence {\n");
            sb.Append("  GeoFencingId: ").Append(GeoFencingId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BasicGeofence);
        }

        /// <summary>
        /// Returns true if BasicGeofence instances are equal
        /// </summary>
        /// <param name="input">Instance of BasicGeofence to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BasicGeofence input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GeoFencingId == input.GeoFencingId ||
                    (this.GeoFencingId != null &&
                    this.GeoFencingId.Equals(input.GeoFencingId))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GeoFencingId != null)
                    hashCode = hashCode * 59 + this.GeoFencingId.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
