/* 
 * ChronoSheets API
 *
 * An API for integrating into ChronoSheets timesheets
 *
 * OpenAPI spec version: v1
 * Contact: lachlan@chronosheets.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = ChronoSheetsAPI.Client.SwaggerDateConverter;

namespace ChronoSheetsAPI.ChronoSheetsClientLibModel
{
    /// <summary>
    /// CsApiSaveOrganisationGroupRequest
    /// </summary>
    [DataContract]
    public partial class CsApiSaveOrganisationGroupRequest :  IEquatable<CsApiSaveOrganisationGroupRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CsApiSaveOrganisationGroupRequest" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="OrganisationGroupName">OrganisationGroupName.</param>
        /// <param name="IsDeleted">IsDeleted.</param>
        public CsApiSaveOrganisationGroupRequest(int? Id = default(int?), string OrganisationGroupName = default(string), bool? IsDeleted = default(bool?))
        {
            this.Id = Id;
            this.OrganisationGroupName = OrganisationGroupName;
            this.IsDeleted = IsDeleted;
        }
        
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id", EmitDefaultValue=false)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or Sets OrganisationGroupName
        /// </summary>
        [DataMember(Name="OrganisationGroupName", EmitDefaultValue=false)]
        public string OrganisationGroupName { get; set; }

        /// <summary>
        /// Gets or Sets IsDeleted
        /// </summary>
        [DataMember(Name="IsDeleted", EmitDefaultValue=false)]
        public bool? IsDeleted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CsApiSaveOrganisationGroupRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OrganisationGroupName: ").Append(OrganisationGroupName).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CsApiSaveOrganisationGroupRequest);
        }

        /// <summary>
        /// Returns true if CsApiSaveOrganisationGroupRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CsApiSaveOrganisationGroupRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CsApiSaveOrganisationGroupRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.OrganisationGroupName == input.OrganisationGroupName ||
                    (this.OrganisationGroupName != null &&
                    this.OrganisationGroupName.Equals(input.OrganisationGroupName))
                ) && 
                (
                    this.IsDeleted == input.IsDeleted ||
                    (this.IsDeleted != null &&
                    this.IsDeleted.Equals(input.IsDeleted))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.OrganisationGroupName != null)
                    hashCode = hashCode * 59 + this.OrganisationGroupName.GetHashCode();
                if (this.IsDeleted != null)
                    hashCode = hashCode * 59 + this.IsDeleted.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
