/* 
 * ChronoSheets API
 *
 * <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ChronoSheetsAPI.Client.OpenAPIDateConverter;

namespace ChronoSheetsAPI.ChronoSheetsClientLibModel
{
    /// <summary>
    /// Fields for saving an existing Vehicle
    /// </summary>
    [DataContract]
    public partial class SaveVehicleRequest :  IEquatable<SaveVehicleRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveVehicleRequest" /> class.
        /// </summary>
        /// <param name="id">The Id of the Vehicle that is being updated.</param>
        /// <param name="name">The Name of the Vehicle.</param>
        /// <param name="costPerKilometer">The fuel cost / running cost of the Vehicle, measured per kilometer.</param>
        /// <param name="make">The make of the Vehicle.</param>
        /// <param name="model">The model of the Vehicle.</param>
        /// <param name="year">The year the Vehicle was made.</param>
        /// <param name="licencePlateNumber">The Licence Plate Number of the Vehicle.</param>
        /// <param name="linkedOrgGroupIds">Optionally restrict this Vehicle to only be available to employees within these Organisation Groups.</param>
        /// <param name="isDeleted">Whether or not this Vehicle is to be marked as deleted.</param>
        public SaveVehicleRequest(int id = default(int), string name = default(string), double costPerKilometer = default(double), string make = default(string), string model = default(string), string year = default(string), string licencePlateNumber = default(string), List<int> linkedOrgGroupIds = default(List<int>), bool isDeleted = default(bool))
        {
            this.Id = id;
            this.Name = name;
            this.CostPerKilometer = costPerKilometer;
            this.Make = make;
            this.Model = model;
            this.Year = year;
            this.LicencePlateNumber = licencePlateNumber;
            this.LinkedOrgGroupIds = linkedOrgGroupIds;
            this.IsDeleted = isDeleted;
        }
        
        /// <summary>
        /// The Id of the Vehicle that is being updated
        /// </summary>
        /// <value>The Id of the Vehicle that is being updated</value>
        [DataMember(Name="Id", EmitDefaultValue=false)]
        public int Id { get; set; }

        /// <summary>
        /// The Name of the Vehicle
        /// </summary>
        /// <value>The Name of the Vehicle</value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// The fuel cost / running cost of the Vehicle, measured per kilometer
        /// </summary>
        /// <value>The fuel cost / running cost of the Vehicle, measured per kilometer</value>
        [DataMember(Name="CostPerKilometer", EmitDefaultValue=false)]
        public double CostPerKilometer { get; set; }

        /// <summary>
        /// The make of the Vehicle
        /// </summary>
        /// <value>The make of the Vehicle</value>
        [DataMember(Name="Make", EmitDefaultValue=false)]
        public string Make { get; set; }

        /// <summary>
        /// The model of the Vehicle
        /// </summary>
        /// <value>The model of the Vehicle</value>
        [DataMember(Name="Model", EmitDefaultValue=false)]
        public string Model { get; set; }

        /// <summary>
        /// The year the Vehicle was made
        /// </summary>
        /// <value>The year the Vehicle was made</value>
        [DataMember(Name="Year", EmitDefaultValue=false)]
        public string Year { get; set; }

        /// <summary>
        /// The Licence Plate Number of the Vehicle
        /// </summary>
        /// <value>The Licence Plate Number of the Vehicle</value>
        [DataMember(Name="LicencePlateNumber", EmitDefaultValue=false)]
        public string LicencePlateNumber { get; set; }

        /// <summary>
        /// Optionally restrict this Vehicle to only be available to employees within these Organisation Groups
        /// </summary>
        /// <value>Optionally restrict this Vehicle to only be available to employees within these Organisation Groups</value>
        [DataMember(Name="LinkedOrgGroupIds", EmitDefaultValue=false)]
        public List<int> LinkedOrgGroupIds { get; set; }

        /// <summary>
        /// Whether or not this Vehicle is to be marked as deleted
        /// </summary>
        /// <value>Whether or not this Vehicle is to be marked as deleted</value>
        [DataMember(Name="IsDeleted", EmitDefaultValue=false)]
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SaveVehicleRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  CostPerKilometer: ").Append(CostPerKilometer).Append("\n");
            sb.Append("  Make: ").Append(Make).Append("\n");
            sb.Append("  Model: ").Append(Model).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("  LicencePlateNumber: ").Append(LicencePlateNumber).Append("\n");
            sb.Append("  LinkedOrgGroupIds: ").Append(LinkedOrgGroupIds).Append("\n");
            sb.Append("  IsDeleted: ").Append(IsDeleted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SaveVehicleRequest);
        }

        /// <summary>
        /// Returns true if SaveVehicleRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SaveVehicleRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SaveVehicleRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.CostPerKilometer == input.CostPerKilometer ||
                    (this.CostPerKilometer != null &&
                    this.CostPerKilometer.Equals(input.CostPerKilometer))
                ) && 
                (
                    this.Make == input.Make ||
                    (this.Make != null &&
                    this.Make.Equals(input.Make))
                ) && 
                (
                    this.Model == input.Model ||
                    (this.Model != null &&
                    this.Model.Equals(input.Model))
                ) && 
                (
                    this.Year == input.Year ||
                    (this.Year != null &&
                    this.Year.Equals(input.Year))
                ) && 
                (
                    this.LicencePlateNumber == input.LicencePlateNumber ||
                    (this.LicencePlateNumber != null &&
                    this.LicencePlateNumber.Equals(input.LicencePlateNumber))
                ) && 
                (
                    this.LinkedOrgGroupIds == input.LinkedOrgGroupIds ||
                    this.LinkedOrgGroupIds != null &&
                    input.LinkedOrgGroupIds != null &&
                    this.LinkedOrgGroupIds.SequenceEqual(input.LinkedOrgGroupIds)
                ) && 
                (
                    this.IsDeleted == input.IsDeleted ||
                    (this.IsDeleted != null &&
                    this.IsDeleted.Equals(input.IsDeleted))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.CostPerKilometer != null)
                    hashCode = hashCode * 59 + this.CostPerKilometer.GetHashCode();
                if (this.Make != null)
                    hashCode = hashCode * 59 + this.Make.GetHashCode();
                if (this.Model != null)
                    hashCode = hashCode * 59 + this.Model.GetHashCode();
                if (this.Year != null)
                    hashCode = hashCode * 59 + this.Year.GetHashCode();
                if (this.LicencePlateNumber != null)
                    hashCode = hashCode * 59 + this.LicencePlateNumber.GetHashCode();
                if (this.LinkedOrgGroupIds != null)
                    hashCode = hashCode * 59 + this.LinkedOrgGroupIds.GetHashCode();
                if (this.IsDeleted != null)
                    hashCode = hashCode * 59 + this.IsDeleted.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
